name: Update Scrobbles

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  deployments: write
  pages: write
  id-token: write

jobs:
  update-scrobbles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Download Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Fetch scrobbles
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
        LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
      run: |
        go mod download
        go run scripts/fetch-scrobbles.go
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/data/scrobbles.json
        git commit -m "Update scrobbles [skip ci]" || exit 0
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Hugo site
      run: |
        hugo --minify
        
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: mcsite
        directory: public 